### ISSUE TITLE
REWIND TV WPIX-DT4 isnt working anymore.

### ISSUE THREAD

**Issue by spotanjo3** [mayaxcn/getM3U8#1]
like Gecko) Chrome/92.0.4515.131 Safari/537.36" group-title="Entertainment",WPIX-DT4 (Rewind TV) (480p)
 like Gecko) Chrome/92.0.4515.131 Safari/537.36,https://v-ny.theus6tv.tk/hls/11.4/playlist.m3u8

**Comment by mayaxcn** [comment]
Sorry,this project is too old.

**Comment by spotanjo3** [comment]
Okay, if this project is too old then what should I do ? Make a new thread to request for Rewind TV WPIX-DT4 m3u8 link ? Since Rewind TV is a free antenna tv, thought.

**Comment by mayaxcn** [comment]
> Okay, if this project is too old then what should I do ? Make a new thread to request for Rewind TV WPIX-DT4 m3u8 link ? Since Rewind TV is a free antenna tv, thought.

Is it (WPIX-DT4) is a news channel? If yes,you can find the m3u8 link in this https://iptv-org.github.io/iptv/categories/news.m3u

**Comment by spotanjo3** [comment]
Umm. This is Sydney channel from Australia. And I am asking for Rewind TV WPIX-DT4 channel. ^_^
