### ISSUE TITLE
REWIND TV LINK IS BROKEN.

### ISSUE THREAD

**Issue by spotanjo3** [mayaxcn/getM3U8#2]
like Gecko) Chrome/92.0.4515.131 Safari/537.36" group-title="Entertainment",WPIX-DT4 (Rewind TV) (480p)
 like Gecko) Chrome/92.0.4515.131 Safari/537.36,https://v-ny.theus6tv.tk/hls/11.4/playlist.m3u8

**Comment by mayaxcn** [comment]
Sorry.This project is too old.
